### ISSUE TITLE
Video embed

### ISSUE THREAD

**Issue by flywebguy** [chrismccoy/fresco#1]
Hi Chris,

Thanks for this repository! Do you have a bitcoin wallet I can send a small donation to?

Quick question: I don't see how to do video embeds from Youtube/Vimeo or even self hosted. Is that something that won't work or am I just missing something?

Here is the page where I'm testing it as an example: http://nonprofit.cinsay.com/fresco-test

Thanks!
Steve

**Comment by morteza-gho** [comment]
Hi :)
What's the cause of this error?!!
Uncaught TypeError: /^([a-zA-Z])+/.cache is not a function

**Comment by chrismccoy** [comment]
any youtube oembed url will be converted to fresco, parsing manual iframes for youtube videos would need a regex on the_content and would rather avoid this

**Comment by chrismccoy** [comment]
1E8e3yooMzUuMB4qqsbyacaJrh2Bagd77y

is my btc address ;)
