### ISSUE TITLE
cache is not a function

### ISSUE THREAD

**Issue by morteza-gho** [chrismccoy/fresco#2]
Hi :)
What's the cause of this error?!!
**Uncaught TypeError: /^([a-zA-Z])+/.cache is not a function**

fresco does not work and the large picture open in window
Thanks

**Comment by chrismccoy** [comment]
what version of wordpress? did you try it with the default theme and only the fresco plugin enabled?

**Comment by morteza-gho** [comment]
I don't use wordpress. i just use only the fresco plugin.

**Comment by chrismccoy** [comment]
then this is not for you, this is a wordpress plugin, you want just the javascript portion, please visit frescojs.com for that.

**Comment by morteza-gho** [comment]
yes i know, but in javascript portion i have this error.

**Comment by morteza-gho** [comment]
yes i know, but in javascript portion i have this error.

On Sun, Apr 24, 2016 at 8:53 AM, Chris McCoy <notifications@github.com>
wrote:

> then this is not for you, this is a wordpress plugin, you want just the
> javascript portion, please visit frescojs.com for that.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/chrismccoy/fresco/issues/2#issuecomment-213882206>
>



-- 
Morteza GhorbanAlizade

**Comment by chrismccoy** [comment]
could be many things, frescojs has their own support forum, where you can ask the developer

**Comment by morteza-gho** [comment]
OK, Thanks :+1:
